<div class="form-section">
    <div class="form-card-heading"><span class="form-section-icon"><svg><use href="#icon-users"></use></svg></span><div><h2>Customer information</h2><p>Enter the customer name and primary contact details.</p></div></div>
    <div class="form-grid">
        <div class="field"><label for="name">Customer Name <span class="required-mark">*</span></label><input class="field-control" id="name" type="text" name="name" value="{{ old('name', isset($customer) ? $customer->name : '') }}" maxlength="255" required>@error('name')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="customer_type">Customer Type <span class="required-mark">*</span></label><select class="field-control" id="customer_type" name="customer_type" required><option value="">Select customer type</option>@foreach ($customerTypes as $type)<option value="{{ $type }}" {{ old('customer_type', isset($customer) ? $customer->customer_type : '') === $type ? 'selected' : '' }}>{{ $type }}</option>@endforeach</select>@error('customer_type')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="contact_person">Contact Person</label><input class="field-control" id="contact_person" type="text" name="contact_person" value="{{ old('contact_person', isset($customer) ? $customer->contact_person : '') }}" maxlength="255">@error('contact_person')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="phone">Phone</label><input class="field-control" id="phone" type="tel" name="phone" value="{{ old('phone', isset($customer) ? $customer->phone : '') }}" maxlength="30" placeholder="e.g. 9988776655">@error('phone')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="email">Email</label><input class="field-control" id="email" type="email" name="email" value="{{ old('email', isset($customer) ? $customer->email : '') }}" maxlength="255">@error('email')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="city">City</label><input class="field-control" id="city" type="text" name="city" value="{{ old('city', isset($customer) ? $customer->city : '') }}" maxlength="255">@error('city')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field field-wide"><label for="address">Address</label><textarea class="field-control" id="address" name="address" rows="3" maxlength="2000">{{ old('address', isset($customer) ? $customer->address : '') }}</textarea>@error('address')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="state">State</label><input class="field-control" id="state" type="text" name="state" value="{{ old('state', isset($customer) ? $customer->state : '') }}" maxlength="255">@error('state')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="pincode">Pincode</label><input class="field-control" id="pincode" type="text" name="pincode" value="{{ old('pincode', isset($customer) ? $customer->pincode : '') }}" maxlength="20">@error('pincode')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="gstin">GSTIN (optional)</label><input class="field-control" id="gstin" type="text" name="gstin" value="{{ old('gstin', isset($customer) ? $customer->gstin : '') }}" maxlength="20">@error('gstin')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="pan">PAN (optional)</label><input class="field-control" id="pan" type="text" name="pan" value="{{ old('pan', isset($customer) ? $customer->pan : '') }}" maxlength="20">@error('pan')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label for="status">Status <span class="required-mark">*</span></label><select class="field-control" id="status" name="status" required><option value="active" {{ old('status', isset($customer) && !$customer->is_active ? 'inactive' : 'active') === 'active' ? 'selected' : '' }}>Active</option><option value="inactive" {{ old('status', isset($customer) && !$customer->is_active ? 'inactive' : 'active') === 'inactive' ? 'selected' : '' }}>Inactive</option></select>@error('status')<small class="field-error">{{ $message }}</small>@enderror</div>
    </div>
</div>
